//
// Created by Auto on 2025/01/XX.
//

#ifndef ZR_VM_LANGUAGE_SERVER_CONF_H
#define ZR_VM_LANGUAGE_SERVER_CONF_H

#include "zr_vm_common.h"

#define ZR_LANGUAGE_SERVER_API ZR_API

#define ZR_LSP_DYNAMIC_CAPACITY_GROWTH_FACTOR 2U

#define ZR_LSP_PROJECT_INDEX_INITIAL_CAPACITY 2U
#define ZR_LSP_ARRAY_INITIAL_CAPACITY 8U
#define ZR_LSP_SMALL_ARRAY_INITIAL_CAPACITY 4U
#define ZR_LSP_LARGE_ARRAY_INITIAL_CAPACITY 16U
#define ZR_LSP_GLOBAL_SCOPE_SYMBOL_INITIAL_CAPACITY ZR_LSP_LARGE_ARRAY_INITIAL_CAPACITY

#define ZR_LSP_HASH_TABLE_INITIAL_SIZE_LOG2 4U
#define ZR_LSP_HASH_MULTIPLIER 31ULL

#define ZR_LSP_NATIVE_GENERIC_ARGUMENT_MAX 8U
#define ZR_LSP_NATIVE_GENERIC_TEXT_MAX 128U

#define ZR_LSP_MARKDOWN_BUFFER_SIZE ZR_VM_PATH_LENGTH_MAX
#define ZR_LSP_SIGNATURE_RANGE_PACK_BASE 4096U

#define ZR_LSP_MEMBER_RECURSION_MAX_DEPTH 8U
#define ZR_LSP_AST_RECURSION_MAX_DEPTH 32U

#define ZR_LSP_SHORT_TEXT_BUFFER_LENGTH 32U
#define ZR_LSP_INTEGER_BUFFER_LENGTH 64U
#define ZR_LSP_TYPE_BUFFER_LENGTH 128U
#define ZR_LSP_COMPLETION_DETAIL_BUFFER_LENGTH 160U
#define ZR_LSP_DETAIL_BUFFER_LENGTH 192U
#define ZR_LSP_TEXT_BUFFER_LENGTH 256U
#define ZR_LSP_LONG_TEXT_BUFFER_LENGTH 512U
#define ZR_LSP_HOVER_BUFFER_LENGTH 1024U
#define ZR_LSP_STDIO_HEADER_BUFFER_LENGTH 1024U
#define ZR_LSP_DOCUMENTATION_BUFFER_LENGTH 2048U

#define ZR_LSP_COMMENT_SCAN_LINE_LIMIT 32U
#define ZR_LSP_COMMENT_BUFFER_LENGTH ZR_LSP_HOVER_BUFFER_LENGTH
#define ZR_LSP_SEMANTIC_TOKEN_INITIAL_CAPACITY 32U

typedef enum EZrLspCompletionItemKind {
    ZR_LSP_COMPLETION_ITEM_KIND_TEXT = 1,
    ZR_LSP_COMPLETION_ITEM_KIND_METHOD = 2,
    ZR_LSP_COMPLETION_ITEM_KIND_FUNCTION = 3,
    ZR_LSP_COMPLETION_ITEM_KIND_FIELD = 5,
    ZR_LSP_COMPLETION_ITEM_KIND_VARIABLE = 6,
    ZR_LSP_COMPLETION_ITEM_KIND_CLASS = 7,
    ZR_LSP_COMPLETION_ITEM_KIND_INTERFACE = 8,
    ZR_LSP_COMPLETION_ITEM_KIND_MODULE = 9,
    ZR_LSP_COMPLETION_ITEM_KIND_PROPERTY = 10,
    ZR_LSP_COMPLETION_ITEM_KIND_ENUM = 13,
    ZR_LSP_COMPLETION_ITEM_KIND_CONSTANT = 21,
    ZR_LSP_COMPLETION_ITEM_KIND_STRUCT = 22,
} EZrLspCompletionItemKind;

typedef enum EZrLspSymbolKind {
    ZR_LSP_SYMBOL_KIND_MODULE = 2,
    ZR_LSP_SYMBOL_KIND_CLASS = 5,
    ZR_LSP_SYMBOL_KIND_METHOD = 6,
    ZR_LSP_SYMBOL_KIND_PROPERTY = 7,
    ZR_LSP_SYMBOL_KIND_FIELD = 8,
    ZR_LSP_SYMBOL_KIND_ENUM = 10,
    ZR_LSP_SYMBOL_KIND_INTERFACE = 11,
    ZR_LSP_SYMBOL_KIND_FUNCTION = 12,
    ZR_LSP_SYMBOL_KIND_VARIABLE = 13,
    ZR_LSP_SYMBOL_KIND_ENUM_MEMBER = 22,
    ZR_LSP_SYMBOL_KIND_STRUCT = 23,
} EZrLspSymbolKind;

#define ZR_LSP_JSON_RPC_PARSE_ERROR_CODE (-32700)
#define ZR_LSP_JSON_RPC_INVALID_REQUEST_CODE (-32600)
#define ZR_LSP_JSON_RPC_METHOD_NOT_FOUND_CODE (-32601)
#define ZR_LSP_JSON_RPC_INVALID_PARAMS_CODE (-32602)

#endif //ZR_VM_LANGUAGE_SERVER_CONF_H
