get_filename_component(ZR_SSA_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

if (NOT TARGET zr_vm_ssa_sccp_phi_copy_edges_test)
    if (NOT TARGET zr_vm_ssa_sccp_conversion_test)
        message(FATAL_ERROR "ssa_sccp_phi_copy_edges requires the current scalar support target")
    endif ()
    get_target_property(_zr_phi_copy_sources zr_vm_ssa_sccp_conversion_test SOURCES)
    list(REMOVE_ITEM _zr_phi_copy_sources
            ${ZR_SSA_SOURCE_ROOT}/tests/parser/test_ssa_sccp_conversion.c)
    list(APPEND _zr_phi_copy_sources
            ${ZR_SSA_SOURCE_ROOT}/tests/parser/test_ssa_sccp_phi_copy_edges.c)
    add_executable(zr_vm_ssa_sccp_phi_copy_edges_test ${_zr_phi_copy_sources})
    get_target_property(_zr_phi_copy_includes zr_vm_ssa_sccp_conversion_test INCLUDE_DIRECTORIES)
    get_target_property(_zr_phi_copy_definitions zr_vm_ssa_sccp_conversion_test COMPILE_DEFINITIONS)
    target_include_directories(zr_vm_ssa_sccp_phi_copy_edges_test PRIVATE ${_zr_phi_copy_includes})
    target_compile_definitions(zr_vm_ssa_sccp_phi_copy_edges_test PRIVATE ${_zr_phi_copy_definitions})
    zr_vm_link_core(zr_vm_ssa_sccp_phi_copy_edges_test)
    add_test(NAME ssa_sccp_phi_copy_edges COMMAND zr_vm_ssa_sccp_phi_copy_edges_test)
    set_tests_properties(ssa_sccp_phi_copy_edges PROPERTIES LABELS "ssa" TIMEOUT 120)
    unset(_zr_phi_copy_sources)
    unset(_zr_phi_copy_includes)
    unset(_zr_phi_copy_definitions)
endif ()
