//
// zr.system.exception descriptor registry.
//

#include "zr_vm_lib_system/exception_registry.h"

#ifndef ZR_ARRAY_COUNT
#define ZR_ARRAY_COUNT(value) (sizeof(value) / sizeof((value)[0]))
#endif

const ZrLibModuleDescriptor *ZrSystem_ExceptionRegistry_GetModule(void) {
    static const ZrLibFieldDescriptor kErrorFields[] = {
            {"message", "string", "Human-readable exception message."},
            {"stacks", "StackFrame[]", "Structured stack frames, throw-site first."},
            {"exception", "value", "Original thrown payload or exception object."},
    };
    static const ZrLibFieldDescriptor kStackFrameFields[] = {
            {"functionName", "string", "Function name for this frame."},
            {"sourceFile", "string", "Source file for this frame."},
            {"sourceLine", "int", "1-based source line for this frame."},
            {"instructionOffset", "int", "Instruction offset inside the function."},
    };
    static const ZrLibMetaMethodDescriptor kExceptionConstructors[] = {
            {ZR_META_CONSTRUCTOR, 0, 1, ZrSystem_Exception_Constructor, "null", "Initialize an exception instance."},
    };
    static const ZrLibTypeDescriptor kTypes[] = {
            {"Error",
             ZR_OBJECT_PROTOTYPE_TYPE_CLASS,
             kErrorFields,
             ZR_ARRAY_COUNT(kErrorFields),
             ZR_NULL,
             0,
             kExceptionConstructors,
             ZR_ARRAY_COUNT(kExceptionConstructors),
             "Base VM exception type.",
             ZR_NULL,
             ZR_NULL,
             0,
             ZR_NULL,
             0,
             ZR_NULL,
             ZR_TRUE,
             ZR_TRUE,
             "Error(message?: any)"},
            {"StackFrame",
             ZR_OBJECT_PROTOTYPE_TYPE_STRUCT,
             kStackFrameFields,
             ZR_ARRAY_COUNT(kStackFrameFields),
             ZR_NULL,
             0,
             ZR_NULL,
             0,
             "Structured VM stack frame.",
             ZR_NULL,
             ZR_NULL,
             0,
             ZR_NULL,
             0,
             ZR_NULL,
             ZR_TRUE,
             ZR_TRUE,
             "StackFrame()"},
            {"RuntimeError",
             ZR_OBJECT_PROTOTYPE_TYPE_CLASS,
             kErrorFields,
             ZR_ARRAY_COUNT(kErrorFields),
             ZR_NULL,
             0,
             kExceptionConstructors,
             ZR_ARRAY_COUNT(kExceptionConstructors),
             "Runtime execution error.",
             "Error",
             ZR_NULL,
             0,
             ZR_NULL,
             0,
             ZR_NULL,
             ZR_TRUE,
             ZR_TRUE,
             "RuntimeError(message?: any)"},
            {"TypeError",
             ZR_OBJECT_PROTOTYPE_TYPE_CLASS,
             kErrorFields,
             ZR_ARRAY_COUNT(kErrorFields),
             ZR_NULL,
             0,
             kExceptionConstructors,
             ZR_ARRAY_COUNT(kExceptionConstructors),
             "Type mismatch error.",
             "Error",
             ZR_NULL,
             0,
             ZR_NULL,
             0,
             ZR_NULL,
             ZR_TRUE,
             ZR_TRUE,
             "TypeError(message?: any)"},
            {"MemoryError",
             ZR_OBJECT_PROTOTYPE_TYPE_CLASS,
             kErrorFields,
             ZR_ARRAY_COUNT(kErrorFields),
             ZR_NULL,
             0,
             kExceptionConstructors,
             ZR_ARRAY_COUNT(kExceptionConstructors),
             "Allocation or memory pressure error.",
             "Error",
             ZR_NULL,
             0,
             ZR_NULL,
             0,
             ZR_NULL,
             ZR_TRUE,
             ZR_TRUE,
             "MemoryError(message?: any)"},
            {"ExceptionError",
             ZR_OBJECT_PROTOTYPE_TYPE_CLASS,
             kErrorFields,
             ZR_ARRAY_COUNT(kErrorFields),
             ZR_NULL,
             0,
             kExceptionConstructors,
             ZR_ARRAY_COUNT(kExceptionConstructors),
             "Generic VM exception state error.",
             "Error",
             ZR_NULL,
             0,
             ZR_NULL,
             0,
             ZR_NULL,
             ZR_TRUE,
             ZR_TRUE,
             "ExceptionError(message?: any)"},
    };
    static const ZrLibFunctionDescriptor kFunctions[] = {
            {"registerUnhandledException",
             1,
             1,
             ZrSystem_Exception_RegisterUnhandledException,
             "null",
             "Register a single global unhandled exception observer."},
    };
    static const ZrLibTypeHintDescriptor kHints[] = {
            {"registerUnhandledException",
             "function",
             "registerUnhandledException(handler: (error: Error) -> bool): null",
             "Register a single global unhandled exception observer."},
            {"Error", "type", "class Error { message, stacks, exception }", "Base VM exception type."},
            {"StackFrame",
             "type",
             "struct StackFrame { functionName, sourceFile, sourceLine, instructionOffset }",
             "Structured VM stack frame."},
            {"RuntimeError", "type", "class RuntimeError extends Error", "Runtime execution error."},
            {"TypeError", "type", "class TypeError extends Error", "Type mismatch error."},
            {"MemoryError", "type", "class MemoryError extends Error", "Allocation or memory pressure error."},
            {"ExceptionError", "type", "class ExceptionError extends Error", "Generic VM exception state error."},
    };
    static const TZrChar kHintsJson[] =
            "{\n"
            "  \"schema\": \"zr.native.hints/v1\",\n"
            "  \"module\": \"zr.system.exception\"\n"
            "}\n";
    static const ZrLibModuleDescriptor kModule = {
            ZR_VM_NATIVE_PLUGIN_ABI_VERSION,
            "zr.system.exception",
            ZR_NULL,
            0,
            kFunctions,
            ZR_ARRAY_COUNT(kFunctions),
            kTypes,
            ZR_ARRAY_COUNT(kTypes),
            kHints,
            ZR_ARRAY_COUNT(kHints),
            kHintsJson,
            "Exception hierarchy and unhandled exception hooks.",
            ZR_NULL,
            0,
    };

    return &kModule;
}
