//
// Created by HeJiahui on 2025/6/15.
//

#ifndef ZR_VM_CORE_TYPE_H
#define ZR_VM_CORE_TYPE_H

enum EZrValueType {
    ZR_VALUE_TYPE_NULL,
    ZR_VALUE_TYPE_BOOL,
    ZR_VALUE_TYPE_INT8,
    ZR_VALUE_TYPE_UINT8,
    ZR_VALUE_TYPE_INT16,
    ZR_VALUE_TYPE_UINT16,
    ZR_VALUE_TYPE_INT32,
    ZR_VALUE_TYPE_UINT32,
    ZR_VALUE_TYPE_INT64,
    ZR_VALUE_TYPE_UINT64,
    ZR_VALUE_TYPE_FLOAT,
    ZR_VALUE_TYPE_DOUBLE,
    ZR_VALUE_TYPE_STRING,
    ZR_VALUE_TYPE_BUFFER,
    ZR_VALUE_TYPE_ARRAY,
    ZR_VALUE_TYPE_FUNCTION,
    ZR_VALUE_TYPE_OBJECT,
    ZR_VALUE_TYPE_NATIVE,

    ZR_VALUE_TYPE_ENUM_MAX
};

typedef enum EZrValueType EZrValueType;
#endif //ZR_VM_CORE_TYPE_H
