//
// Created by Auto on 2025/01/XX.
//

#ifndef ZR_AST_CONSTANTS_H
#define ZR_AST_CONSTANTS_H

#include "zr_vm_common/zr_common_conf.h"

// AST节点类型常量（用于序列化数据，避免依赖parser模块）
// 这些值必须与zr_vm_parser/ast.h中的EZrAstNodeType枚举值保持一致
// 枚举值从0开始连续计数：
// ZR_AST_SCRIPT=0, ZR_AST_MODULE_DECLARATION=1, ..., ZR_AST_INTERMEDIATE_STATEMENT=9
// ZR_AST_STRUCT_FIELD=10, ZR_AST_STRUCT_METHOD=11, ZR_AST_STRUCT_META_FUNCTION=12
// ZR_AST_CLASS_FIELD=13, ZR_AST_CLASS_METHOD=14, ZR_AST_CLASS_PROPERTY=15, ZR_AST_CLASS_META_FUNCTION=16
#define ZR_AST_CONSTANT_STRUCT_FIELD 10
#define ZR_AST_CONSTANT_STRUCT_METHOD 11
#define ZR_AST_CONSTANT_STRUCT_META_FUNCTION 12
#define ZR_AST_CONSTANT_CLASS_FIELD 13
#define ZR_AST_CONSTANT_CLASS_METHOD 14
#define ZR_AST_CONSTANT_CLASS_PROPERTY 15
#define ZR_AST_CONSTANT_CLASS_META_FUNCTION 16

// 访问修饰符常量（用于序列化数据，避免依赖parser模块）
// 这些值必须与zr_vm_parser/ast.h中的EZrAccessModifier枚举值保持一致
#define ZR_ACCESS_CONSTANT_PUBLIC 0
#define ZR_ACCESS_CONSTANT_PRIVATE 1
#define ZR_ACCESS_CONSTANT_PROTECTED 2

#endif // ZR_AST_CONSTANTS_H
