//
// Stable contract-role identifiers shared by compiler, runtime and native metadata.
//

#ifndef ZR_VM_COMMON_ZR_CONTRACT_CONF_H
#define ZR_VM_COMMON_ZR_CONTRACT_CONF_H

#include "zr_vm_common/zr_common_conf.h"

#define ZR_TYPE_MODIFIER_FLAG_RESOURCE (1u << 8)

typedef enum EZrMemberContractRole {
    ZR_MEMBER_CONTRACT_ROLE_NONE = 0,
    ZR_MEMBER_CONTRACT_ROLE_ITERABLE_INIT = 1,
    ZR_MEMBER_CONTRACT_ROLE_ITERATOR_MOVE_NEXT = 2,
    ZR_MEMBER_CONTRACT_ROLE_ITERATOR_CURRENT_METHOD = 3,
    ZR_MEMBER_CONTRACT_ROLE_ITERATOR_CURRENT_FIELD = 4,
    ZR_MEMBER_CONTRACT_ROLE_INDEX_LENGTH = 5,
    ZR_MEMBER_CONTRACT_ROLE_BUILTIN_BOX = 6,
    ZR_MEMBER_CONTRACT_ROLE_TASK_AWAIT = 7,
    ZR_MEMBER_CONTRACT_ROLE_CONTIGUOUS_VIEW_SOURCE = 8,
    ZR_MEMBER_CONTRACT_ROLE_CONTIGUOUS_VIEW_START = 9,
    ZR_MEMBER_CONTRACT_ROLE_CONTIGUOUS_VIEW_SLICE = 10,
    ZR_MEMBER_CONTRACT_ROLE_READONLY_VIEW_CONVERSION = 11,
    ZR_MEMBER_CONTRACT_ROLE_CONTIGUOUS_VIEW_CREATE = 12,
    ZR_MEMBER_CONTRACT_ROLE_ASYNC_ITERATOR_MOVE_NEXT = 13,
    ZR_MEMBER_CONTRACT_ROLE_ASYNC_ITERATOR_CURRENT_FIELD = 14,
    ZR_MEMBER_CONTRACT_ROLE_ASYNC_ITERATOR_CLOSE = 15,
    ZR_MEMBER_CONTRACT_ROLE_TASK_JOB_CONSTRUCT = 16,
    ZR_MEMBER_CONTRACT_ROLE_TASK_SCHEDULER_SCHEDULE = 17,
    ZR_MEMBER_CONTRACT_ROLE_TASK_CURRENT_SCHEDULER = 18,
    ZR_MEMBER_CONTRACT_ROLE_TASK_YIELD_NOW = 19,
    ZR_MEMBER_CONTRACT_ROLE_TASK_DELAY = 20,
    ZR_MEMBER_CONTRACT_ROLE_POOL_HANDLE_POOL_ID = 21,
    ZR_MEMBER_CONTRACT_ROLE_POOL_HANDLE_SLOT = 22,
    ZR_MEMBER_CONTRACT_ROLE_POOL_HANDLE_GENERATION = 23,
    ZR_MEMBER_CONTRACT_ROLE_POOL_DELIVER = 24,
    ZR_MEMBER_CONTRACT_ROLE_POOL_VALIDATE = 25,
    ZR_MEMBER_CONTRACT_ROLE_POOL_RECYCLE = 26,
    ZR_MEMBER_CONTRACT_ROLE_POOL_ACQUIRE_READ = 27,
    ZR_MEMBER_CONTRACT_ROLE_POOL_ACQUIRE_WRITE = 28,
    ZR_MEMBER_CONTRACT_ROLE_POOL_RELEASE = 29,
    ZR_MEMBER_CONTRACT_ROLE_POOL_REF_PROJECTION = 30
} EZrMemberContractRole;

typedef enum EZrProviderContractRole {
    ZR_PROVIDER_CONTRACT_ROLE_NONE = 0,
    ZR_PROVIDER_CONTRACT_ROLE_BUILTIN_TYPE_SURFACE = 1,
    ZR_PROVIDER_CONTRACT_ROLE_REFLECTION = 2
} EZrProviderContractRole;

typedef enum EZrCanonicalTypeRole {
    ZR_CANONICAL_TYPE_ROLE_NONE = 0,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_ROOT = 1,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_CLASS = 2,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_STRUCT = 3,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_FUNCTION = 4,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_FIELD = 5,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_METHOD = 6,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_PROPERTY = 7,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_PARAMETER = 8,
    ZR_CANONICAL_TYPE_ROLE_BUILTIN_METADATA_OBJECT = 9,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE = 10,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_ID = 11,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF = 12,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_CLASS_TYPE_OF = 13,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_CONCRETE_CLASS_TYPE_OF = 14,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_INSTANCE_CLASS_TYPE_OF = 15,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_STRUCT_TYPE_OF = 16,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_INTERFACE_TYPE_OF = 17,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_RESOURCE_CLASS_TYPE_OF = 18,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_REF_STRUCT_TYPE_OF = 19,
    ZR_CANONICAL_TYPE_ROLE_REFLECTION_ENUM_TYPE_OF = 20
} EZrCanonicalTypeRole;

typedef enum EZrCanonicalTypeSurfaceFlag {
    ZR_CANONICAL_TYPE_SURFACE_NONE = 0,
    ZR_CANONICAL_TYPE_SURFACE_METADATA_MEMBERS = 1u << 0u,
    ZR_CANONICAL_TYPE_SURFACE_CALLABLE_MEMBERS = 1u << 1u,
    ZR_CANONICAL_TYPE_SURFACE_RUNTIME_TYPE_MEMBERS = 1u << 2u,
    ZR_CANONICAL_TYPE_SURFACE_REPRESENTED_TYPE_ID = 1u << 3u,
    ZR_CANONICAL_TYPE_SURFACE_CONSTRUCTIBLE = 1u << 4u
} EZrCanonicalTypeSurfaceFlag;

typedef enum EZrCanonicalTypeProjectionKind {
    ZR_CANONICAL_TYPE_PROJECTION_ERASED = 0,
    ZR_CANONICAL_TYPE_PROJECTION_CLASS = 1,
    ZR_CANONICAL_TYPE_PROJECTION_CONCRETE_CLASS = 2,
    ZR_CANONICAL_TYPE_PROJECTION_INSTANCE_CLASS = 3,
    ZR_CANONICAL_TYPE_PROJECTION_STRUCT = 4,
    ZR_CANONICAL_TYPE_PROJECTION_INTERFACE = 5,
    ZR_CANONICAL_TYPE_PROJECTION_RESOURCE_CLASS = 6,
    ZR_CANONICAL_TYPE_PROJECTION_REF_STRUCT = 7,
    ZR_CANONICAL_TYPE_PROJECTION_ENUM = 8
} EZrCanonicalTypeProjectionKind;

#endif // ZR_VM_COMMON_ZR_CONTRACT_CONF_H
