//
// Created by HeJiahui on 2025/8/10.
//

#ifndef ZR_MEMORY_CONF_H
#define ZR_MEMORY_CONF_H

/** @brief 原生内存分配的类别标签；分配器与诊断统计以此区分 VM 内部资源。
 *  它不表示 GC 对象类型，不能用于判断对象存活或回收方式。 */
enum EZrMemoryNativeType {
    ZR_MEMORY_NATIVE_TYPE_NONE,

    ZR_MEMORY_NATIVE_TYPE_MANAGER,
    ZR_MEMORY_NATIVE_TYPE_STATE,
    ZR_MEMORY_NATIVE_TYPE_GLOBAL,
    ZR_MEMORY_NATIVE_TYPE_STACK,

    ZR_MEMORY_NATIVE_TYPE_STRING,
    ZR_MEMORY_NATIVE_TYPE_NATIVE_STRING,
    ZR_MEMORY_NATIVE_TYPE_HASH_PAIR,
    ZR_MEMORY_NATIVE_TYPE_HASH_BUCKET,
    ZR_MEMORY_NATIVE_TYPE_IO,
    ZR_MEMORY_NATIVE_TYPE_OBJECT,
    ZR_MEMORY_NATIVE_TYPE_FUNCTION,
    ZR_MEMORY_NATIVE_TYPE_CALL_INFO,
    ZR_MEMORY_NATIVE_TYPE_ARRAY,


    ZR_MEMORY_NATIVE_TYPE_FILE_BUFFER,
    ZR_MEMORY_NATIVE_TYPE_PROJECT,


    ZR_MEMORY_NATIVE_TYPE_ENUM_MAX,
};

typedef enum EZrMemoryNativeType EZrMemoryNativeType;

#endif // ZR_MEMORY_CONF_H
