//
// Created by HeJiahui on 2025/6/18.
//

#ifndef ZR_OBJECT_CONF_H
#define ZR_OBJECT_CONF_H

#include "zr_vm_common/zr_type_conf.h"

#if defined(ZR_DEBUG)
#define ZR_DEBUG_GARBAGE_COLLECT_MEM_TEST
#endif

#define ZR_GARBAGE_COLLECT_DEBT_SIZE (-2000)
#define ZR_GARBAGE_COLLECT_MINOR_MULTIPLIER 20
#define ZR_GARBAGE_COLLECT_MAJOR_MULTIPLIER 100
#define ZR_GARBAGE_COLLECT_STEP_MULTIPLIER_PERCENT 100
// how much to allocate before next GC step (log2)
#define ZR_GARBAGE_COLLECT_STEP_LOG2_SIZE 17 /* 128KB */
// wait memory to 200% before starting new gc cycle
#define ZR_GARBAGE_COLLECT_PAUSE_THRESHOLD_PERCENT 200
#define ZR_GC_SCOPE_DEPTH_NONE ((TZrUInt32)0xFFFFFFFFu)


enum EZrGarbageCollectMode {
    ZR_GARBAGE_COLLECT_MODE_GENERATIONAL,
    ZR_GARBAGE_COLLECT_MODE_INCREMENTAL,
    ZR_GARBAGE_COLLECT_MODE_MAX
};

typedef enum EZrGarbageCollectMode EZrGarbageCollectMode;


enum EZrGarbageCollectIncrementalObjectStatus {
    // gc ignore
    ZR_GARBAGE_COLLECT_INCREMENTAL_OBJECT_STATUS_PERMANENT,
    // (white) still not scanned on this turn
    ZR_GARBAGE_COLLECT_INCREMENTAL_OBJECT_STATUS_INITED,
    // (gray) object is referenced but its children remain unscanned
    ZR_GARBAGE_COLLECT_INCREMENTAL_OBJECT_STATUS_WAIT_TO_SCAN,
    // (black) scanned and marked as referenced
    ZR_GARBAGE_COLLECT_INCREMENTAL_OBJECT_STATUS_REFERENCED,
    // (white) not referenced and wait to be released
    ZR_GARBAGE_COLLECT_INCREMENTAL_OBJECT_STATUS_UNREFERENCED,
    // (white) mark destructed object as released
    ZR_GARBAGE_COLLECT_INCREMENTAL_OBJECT_STATUS_RELEASED,

    ZR_GARBAGE_COLLECT_INCREMENTAL_OBJECT_STATUS_MAX
};

typedef enum EZrGarbageCollectIncrementalObjectStatus EZrGarbageCollectIncrementalObjectStatus;

enum EZrGarbageCollectGenerationalObjectStatus {
    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_NEW,
    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_SURVIVAL,
    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_BARRIER,
    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_ALIVE,
    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_LONG_ALIVE,
    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_SCANNED,
    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_SCANNED_PREVIOUS,

    ZR_GARBAGE_COLLECT_GENERATIONAL_OBJECT_STATUS_MAX
};

typedef enum EZrGarbageCollectGenerationalObjectStatus EZrGarbageCollectGenerationalObjectStatus;

enum EZrGarbageCollectStatus {
    ZR_GARBAGE_COLLECT_STATUS_RUNNING,
    ZR_GARBAGE_COLLECT_STATUS_STOP_BY_USER,
    ZR_GARBAGE_COLLECT_STATUS_STOP_BY_SELF,
    ZR_GARBAGE_COLLECT_STATUS_STOP_BY_EXITING,
    ZR_GARBAGE_COLLECT_STATUS_MAX,
};

typedef enum EZrGarbageCollectStatus EZrGarbageCollectStatus;

enum EZrGarbageCollectRunningStatus {
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_FLAG_PROPAGATION,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_BEFORE_ATOMIC,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_ATOMIC,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_SWEEP_OBJECTS,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_SWEEP_WAIT_TO_RELEASE_OBJECTS,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_SWEEP_RELEASED_OBJECTS,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_SWEEP_END,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_END,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_PAUSED,
    ZR_GARBAGE_COLLECT_RUNNING_STATUS_MAX
};

typedef enum EZrGarbageCollectRunningStatus EZrGarbageCollectRunningStatus;

enum EZrGarbageCollectGeneration {
    ZR_GARBAGE_COLLECT_GENERATION_INVALID,
    ZR_GARBAGE_COLLECT_GENERATION_A,
    ZR_GARBAGE_COLLECT_GENERATION_B,
};

typedef enum EZrGarbageCollectGeneration EZrGarbageCollectGeneration;

enum EZrGarbageCollectHeapGenerationKind {
    ZR_GARBAGE_COLLECT_HEAP_GENERATION_KIND_YOUNG = 0,
    ZR_GARBAGE_COLLECT_HEAP_GENERATION_KIND_OLD = 1,
    ZR_GARBAGE_COLLECT_HEAP_GENERATION_KIND_PERMANENT = 2,
    ZR_GARBAGE_COLLECT_HEAP_GENERATION_KIND_MAX
};

typedef enum EZrGarbageCollectHeapGenerationKind EZrGarbageCollectHeapGenerationKind;

enum EZrGarbageCollectRegionKind {
    ZR_GARBAGE_COLLECT_REGION_KIND_INVALID = 0,
    ZR_GARBAGE_COLLECT_REGION_KIND_EDEN = 1,
    ZR_GARBAGE_COLLECT_REGION_KIND_SURVIVOR = 2,
    ZR_GARBAGE_COLLECT_REGION_KIND_OLD = 3,
    ZR_GARBAGE_COLLECT_REGION_KIND_PINNED = 4,
    ZR_GARBAGE_COLLECT_REGION_KIND_LARGE = 5,
    ZR_GARBAGE_COLLECT_REGION_KIND_PERMANENT = 6,
    ZR_GARBAGE_COLLECT_REGION_KIND_MAX
};

typedef enum EZrGarbageCollectRegionKind EZrGarbageCollectRegionKind;

enum EZrGarbageCollectStorageKind {
    ZR_GARBAGE_COLLECT_STORAGE_KIND_YOUNG_MOVABLE = 0,
    ZR_GARBAGE_COLLECT_STORAGE_KIND_OLD_MOVABLE = 1,
    ZR_GARBAGE_COLLECT_STORAGE_KIND_OLD_PINNED = 2,
    ZR_GARBAGE_COLLECT_STORAGE_KIND_LARGE_PERSISTENT = 3,
    ZR_GARBAGE_COLLECT_STORAGE_KIND_MAX
};

typedef enum EZrGarbageCollectStorageKind EZrGarbageCollectStorageKind;

enum EZrGarbageCollectEscapeKind {
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_NONE = 0,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_RETURN = 1 << 0,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_CLOSURE_CAPTURE = 1 << 1,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_MODULE_ROOT = 1 << 2,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_GLOBAL_ROOT = 1 << 3,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_HOST_HANDLE = 1 << 4,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_OLD_REFERENCE = 1 << 5,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_PINNED_REFERENCE = 1 << 6,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_CROSS_THREAD = 1 << 7,
    ZR_GARBAGE_COLLECT_ESCAPE_KIND_NATIVE_HANDLE = 1 << 8
};

typedef enum EZrGarbageCollectEscapeKind EZrGarbageCollectEscapeKind;

enum EZrGarbageCollectPinKind {
    ZR_GARBAGE_COLLECT_PIN_KIND_NONE = 0,
    ZR_GARBAGE_COLLECT_PIN_KIND_HOST_HANDLE = 1 << 0,
    ZR_GARBAGE_COLLECT_PIN_KIND_NATIVE_HANDLE = 1 << 1,
    ZR_GARBAGE_COLLECT_PIN_KIND_PERSISTENT_ROOT = 1 << 2,
    ZR_GARBAGE_COLLECT_PIN_KIND_LARGE_OBJECT = 1 << 3
};

typedef enum EZrGarbageCollectPinKind EZrGarbageCollectPinKind;

enum EZrGarbageCollectPromotionReason {
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_NONE = 0,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_SURVIVAL = 1,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_ESCAPE = 2,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_OLD_REFERENCE = 3,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_PINNED = 4,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_MODULE_ROOT = 5,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_GLOBAL_ROOT = 6,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_HOST_HANDLE = 7,
    ZR_GARBAGE_COLLECT_PROMOTION_REASON_LARGE_OBJECT = 8
};

typedef enum EZrGarbageCollectPromotionReason EZrGarbageCollectPromotionReason;

enum EZrRawObjectType {
    ZR_RAW_OBJECT_TYPE_INVALID,
    ZR_RAW_OBJECT_TYPE_STRING = ZR_VALUE_TYPE_STRING,
    ZR_RAW_OBJECT_TYPE_BUFFER = ZR_VALUE_TYPE_BUFFER,
    ZR_RAW_OBJECT_TYPE_ARRAY = ZR_VALUE_TYPE_ARRAY,
    ZR_RAW_OBJECT_TYPE_FUNCTION = ZR_VALUE_TYPE_FUNCTION,
    ZR_RAW_OBJECT_TYPE_CLOSURE_VALUE = ZR_VALUE_TYPE_CLOSURE_VALUE,
    ZR_RAW_OBJECT_TYPE_CLOSURE = ZR_VALUE_TYPE_CLOSURE,
    ZR_RAW_OBJECT_TYPE_OBJECT = ZR_VALUE_TYPE_OBJECT,
    ZR_RAW_OBJECT_TYPE_THREAD = ZR_VALUE_TYPE_THREAD,
    ZR_RAW_OBJECT_TYPE_NATIVE_POINTER = ZR_VALUE_TYPE_NATIVE_POINTER,
    ZR_RAW_OBJECT_TYPE_NATIVE_DATA = ZR_VALUE_TYPE_NATIVE_DATA,

    ZR_RAW_OBJECT_TYPE_CLOSURE_ENUM_MAX
};

typedef enum EZrRawObjectType EZrRawObjectType;

enum EZrObjectPrototypeType {
    ZR_OBJECT_PROTOTYPE_TYPE_INVALID,
    ZR_OBJECT_PROTOTYPE_TYPE_MODULE,
    ZR_OBJECT_PROTOTYPE_TYPE_CLASS,
    ZR_OBJECT_PROTOTYPE_TYPE_INTERFACE,
    ZR_OBJECT_PROTOTYPE_TYPE_STRUCT,
    ZR_OBJECT_PROTOTYPE_TYPE_ENUM,
    ZR_OBJECT_PROTOTYPE_TYPE_NATIVE,
    ZR_OBJECT_PROTOTYPE_TYPE_MAX
};

typedef enum EZrObjectPrototypeType EZrObjectPrototypeType;

struct SZrGarbageCollectionObjectMark {
    EZrGarbageCollectIncrementalObjectStatus status;
    EZrGarbageCollectGenerationalObjectStatus generationalStatus;
    EZrGarbageCollectGeneration generation;
    EZrGarbageCollectHeapGenerationKind heapGenerationKind;
    EZrGarbageCollectRegionKind regionKind;
    EZrGarbageCollectStorageKind storageKind;
    TZrUInt32 regionId;
    TZrUInt32 survivalAge;
    TZrUInt32 escapeFlags;
    TZrUInt32 anchorScopeDepth;
    TZrUInt32 pinFlags;
    EZrGarbageCollectPromotionReason promotionReason;
    TZrPtr forwardingAddress;
    TZrPtr forwardingRefLocation;
};

typedef struct SZrGarbageCollectionObjectMark SZrGarbageCollectionObjectMark;


#endif // ZR_OBJECT_CONF_H
