//
// Shared parser and compiler recovery limits.
//

#ifndef ZR_PARSER_CONF_H
#define ZR_PARSER_CONF_H

#include "zr_vm_common/zr_common_conf.h"

#define ZR_PARSER_LEXER_BUFFER_INITIAL_SIZE 256U
#define ZR_PARSER_MAX_CONSECUTIVE_ERRORS 10U
#define ZR_PARSER_MAX_RECOVERY_SKIP_TOKENS 100U
#define ZR_PARSER_COMPILE_TIME_RUNTIME_SAFE_MAX_DEPTH 64U

#define ZR_PARSER_RECURSIVE_MEMBER_LOOKUP_MAX_DEPTH 32U
#define ZR_PARSER_DYNAMIC_CAPACITY_GROWTH_FACTOR 2U

#define ZR_PARSER_INITIAL_CAPACITY_PAIR 2U
#define ZR_PARSER_INITIAL_CAPACITY_TINY 4U
#define ZR_PARSER_INITIAL_CAPACITY_SMALL 8U
#define ZR_PARSER_INITIAL_CAPACITY_MEDIUM 16U
#define ZR_PARSER_INITIAL_CAPACITY_LARGE 32U
#define ZR_PARSER_INSTRUCTION_INITIAL_CAPACITY 64U

#define ZR_PARSER_U32_NONE ((TZrUInt32)0xFFFFFFFFu)
#define ZR_PARSER_I32_NONE ((TZrInt32)-1)
#define ZR_PARSER_SLOT_NONE ZR_PARSER_U32_NONE
#define ZR_PARSER_MEMBER_ID_NONE ZR_PARSER_U32_NONE
#define ZR_PARSER_INDEX_NONE ZR_PARSER_U32_NONE
#define ZR_PARSER_LABEL_ID_NONE ((TZrSize)-1)
#define ZR_PARSER_LEXER_EOZ ((TZrInt32)-1)

#define ZR_PARSER_ARRAY_SIZE_BUFFER_LENGTH 32U
#define ZR_PARSER_INTEGER_BUFFER_LENGTH 64U
#define ZR_PARSER_GENERATED_NAME_BUFFER_LENGTH 96U
#define ZR_PARSER_TYPE_NAME_BUFFER_LENGTH 128U
#define ZR_PARSER_DETAIL_BUFFER_LENGTH 160U
#define ZR_PARSER_ERROR_SNIPPET_CONTEXT_RADIUS 20U
#define ZR_PARSER_ERROR_SNIPPET_FOCUS_COLUMN (ZR_PARSER_ERROR_SNIPPET_CONTEXT_RADIUS + 1U)
#define ZR_PARSER_ERROR_BUFFER_LENGTH 256U
#define ZR_PARSER_TEXT_BUFFER_LENGTH 512U
#define ZR_PARSER_DECLARATION_BUFFER_LENGTH 1024U

#endif // ZR_PARSER_CONF_H
