//
// Shared runtime sizing and fallback limits.
//

#ifndef ZR_RUNTIME_LIMITS_CONF_H
#define ZR_RUNTIME_LIMITS_CONF_H

#include "zr_vm_common/zr_common_conf.h"

/* global 层共享 API 字符串与拼接缓存容量；两组键空间分开，避免把缓存限额误用作用户可见长度。 */
#define ZR_GLOBAL_API_STRING_CACHE_BUCKET_COUNT 193U
#define ZR_GLOBAL_API_STRING_CACHE_BUCKET_DEPTH 2U
#define ZR_GLOBAL_CONCAT_PAIR_CACHE_BUCKET_COUNT 29U
#define ZR_GLOBAL_CONCAT_PAIR_CACHE_BUCKET_DEPTH 2U

#define ZR_STRING_TABLE_INITIAL_SIZE_LOG2 12U
#define ZR_OBJECT_TABLE_INITIAL_SIZE_LOG2 2U

/* native 调用进入 VM 前需预留栈和错误处理空间，防止失败报告自身再次耗尽栈。 */
#define ZR_STACK_NATIVE_CALL_RESERVED_MIN 20U
#define ZR_NATIVE_CALL_STACK_ERROR_HANDLER_GUARD_DIVISOR 10U
#define ZR_NATIVE_CALL_STACK_ERROR_HANDLER_GUARD_MULTIPLIER 11U
#define ZR_VM_READ_ALL_IO_FALLBACK_CAPACITY 4096U

/* 以下容量分别供诊断/反射临时文本及对象调用/原型表使用；格式化调用方须自行处理截断。 */
#define ZR_RUNTIME_SMALL_TEXT_BUFFER_LENGTH 64U
#define ZR_RUNTIME_MEMBER_NAME_BUFFER_LENGTH 32U
#define ZR_RUNTIME_TYPE_NAME_BUFFER_LENGTH 128U
#define ZR_RUNTIME_DIAGNOSTIC_BUFFER_LENGTH 256U
#define ZR_RUNTIME_QUALIFIED_NAME_BUFFER_LENGTH 512U
#define ZR_RUNTIME_ERROR_BUFFER_LENGTH 1024U
#define ZR_RUNTIME_DEBUG_STRING_BUFFER_LENGTH 2048U
#define ZR_RUNTIME_DEBUG_COLLECTION_PREVIEW_MAX 10U
#define ZR_RUNTIME_REFLECTION_FORMAT_BUFFER_LENGTH 8192U
#define ZR_RUNTIME_OBJECT_CALL_INLINE_ARGUMENT_CAPACITY 8U
#define ZR_RUNTIME_OBJECT_PROTOTYPE_INITIAL_CAPACITY 4U
#define ZR_RUNTIME_OBJECT_PROTOTYPE_GROWTH_FACTOR 2U
#define ZR_RUNTIME_PROTOTYPE_INHERIT_INITIAL_CAPACITY 4U

#endif // ZR_RUNTIME_LIMITS_CONF_H
