//
// Created by HeJiahui on 2025/6/5.
//

#ifndef ZR_TYPE_CONF_H
#define ZR_TYPE_CONF_H


#include "zr_vm_common/zr_common_conf.h"

//
enum EZrValueType {
    ZR_VALUE_TYPE_NULL,
    ZR_VALUE_TYPE_BOOL,
    ZR_VALUE_TYPE_INT8,
    ZR_VALUE_TYPE_UINT8,
    ZR_VALUE_TYPE_INT16,
    ZR_VALUE_TYPE_UINT16,
    ZR_VALUE_TYPE_INT32,
    ZR_VALUE_TYPE_UINT32,
    ZR_VALUE_TYPE_INT64,
    ZR_VALUE_TYPE_UINT64,
    ZR_VALUE_TYPE_FLOAT,
    ZR_VALUE_TYPE_DOUBLE,
    ZR_VALUE_TYPE_STRING,
    ZR_VALUE_TYPE_BUFFER,
    ZR_VALUE_TYPE_ARRAY,
    ZR_VALUE_TYPE_FUNCTION,
    ZR_VALUE_TYPE_OBJECT,
    ZR_VALUE_TYPE_NATIVE_POINTER,
    ZR_VALUE_TYPE_NATIVE_DATA,
    ZR_VALUE_TYPE_THREAD,


    ZR_VALUE_TYPE_UNKNOWN,
    ZR_VALUE_TYPE_ENUM_MAX
};

typedef enum EZrValueType EZrValueType;


#endif //ZR_TYPE_CONF_H
