#ifndef ZR_VM_LIB_NETWORK_CONF_H
#define ZR_VM_LIB_NETWORK_CONF_H

#include "zr_vm_common.h"

#define ZR_NETWORK_API ZR_API

#define ZR_NETWORK_ENDPOINT_TEXT_CAPACITY 96U
#define ZR_NETWORK_FRAME_BUFFER_CAPACITY 8192U
#define ZR_NETWORK_WAIT_INFINITE ((TZrUInt32) 0xFFFFFFFFu)

#endif
