//
// Created by HeJiahui on 2025/6/5.
//

#ifndef ZR_VM_LIBRARY_CONF_H
#define ZR_VM_LIBRARY_CONF_H

#include "zr_vm_common.h"
#include "zr_vm_core.h"

#define ZR_LIBRARY_API ZR_API

#define ZR_LIBRARY_MAX_PATH_LENGTH (ZR_VM_PATH_LENGTH_MAX)
#define ZR_LIBRARY_NATIVE_MODULE_RECORDS_INITIAL_CAPACITY 8U
#define ZR_LIBRARY_NATIVE_BINDING_ENTRIES_INITIAL_CAPACITY 64U
#define ZR_LIBRARY_NATIVE_PLUGIN_HANDLES_INITIAL_CAPACITY 4U
#define ZR_LIBRARY_NATIVE_INLINE_ARGUMENT_CAPACITY 8U
#define ZR_LIBRARY_NATIVE_REGISTRY_ERROR_BUFFER_LENGTH 512U

#endif // ZR_VM_LIBRARY_CONF_H
