#include "native_binding_internal.h"

static const ZrLibCanonicalTypeRoleDescriptor k_reflection_canonical_type_roles[] = {
        {"zr.reflection.Type",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE,
         ZR_CANONICAL_TYPE_ROLE_NONE,
         ZR_CANONICAL_TYPE_SURFACE_RUNTIME_TYPE_MEMBERS,
         ZR_CANONICAL_TYPE_PROJECTION_ERASED},
        {"zr.reflection.TypeId",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_ID,
         ZR_CANONICAL_TYPE_ROLE_NONE,
         ZR_CANONICAL_TYPE_SURFACE_NONE,
         ZR_CANONICAL_TYPE_PROJECTION_ERASED},
        {"zr.reflection.TypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE,
         ZR_CANONICAL_TYPE_SURFACE_REPRESENTED_TYPE_ID,
         ZR_CANONICAL_TYPE_PROJECTION_ERASED},
        {"zr.reflection.declaration.ClassTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_CLASS_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_NONE,
         ZR_CANONICAL_TYPE_PROJECTION_CLASS},
        {"zr.reflection.declaration.ConcreteClassTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_CONCRETE_CLASS_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_CLASS_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_CONSTRUCTIBLE,
         ZR_CANONICAL_TYPE_PROJECTION_CONCRETE_CLASS},
        {"zr.reflection.declaration.InstanceClassTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_INSTANCE_CLASS_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_CONCRETE_CLASS_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_NONE,
         ZR_CANONICAL_TYPE_PROJECTION_INSTANCE_CLASS},
        {"zr.reflection.declaration.StructTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_STRUCT_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_CONSTRUCTIBLE,
         ZR_CANONICAL_TYPE_PROJECTION_STRUCT},
        {"zr.reflection.declaration.InterfaceTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_INTERFACE_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_NONE,
         ZR_CANONICAL_TYPE_PROJECTION_INTERFACE},
        {"zr.reflection.declaration.ResourceClassTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_RESOURCE_CLASS_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_NONE,
         ZR_CANONICAL_TYPE_PROJECTION_RESOURCE_CLASS},
        {"zr.reflection.declaration.RefStructTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_REF_STRUCT_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_NONE,
         ZR_CANONICAL_TYPE_PROJECTION_REF_STRUCT},
        {"zr.reflection.declaration.EnumTypeOf",
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_ENUM_TYPE_OF,
         ZR_CANONICAL_TYPE_ROLE_REFLECTION_TYPE_OF,
         ZR_CANONICAL_TYPE_SURFACE_NONE,
         ZR_CANONICAL_TYPE_PROJECTION_ENUM},
};

static const ZrLibModuleDescriptor k_reflection_contract_descriptor = {
        .abiVersion = ZR_VM_NATIVE_PLUGIN_ABI_VERSION,
        .moduleName = "zr.reflection",
        .documentation = "Runtime-bound reflection service and canonical descriptor type contract.",
        .moduleVersion = "1.0.0",
        .minRuntimeAbi = ZR_VM_NATIVE_RUNTIME_ABI_VERSION,
        .providerPhase = ZR_LIBRARY_PROVIDER_PHASE_RUNTIME,
        .publicContractHash = "zr.reflection.contract.v1",
        .providerContractRole = ZR_PROVIDER_CONTRACT_ROLE_REFLECTION,
        .canonicalTypeRoles = k_reflection_canonical_type_roles,
        .canonicalTypeRoleCount = ZR_ARRAY_COUNT(k_reflection_canonical_type_roles),
        .isContractOnly = ZR_TRUE,
};

const ZrLibModuleDescriptor *ZrLibrary_ReflectionContract_GetDescriptor(void) {
    return &k_reflection_contract_descriptor;
}
