#ifndef ZR_VM_PARSER_BACKEND_AOT_C_ZRP_METADATA_TYPE_SPEC_H
#define ZR_VM_PARSER_BACKEND_AOT_C_ZRP_METADATA_TYPE_SPEC_H

#include "backend_aot_c_zrp_metadata_signature.h"
#include "backend_aot_function_table.h"

#include "zr_vm_core/metadata_token.h"
#include "zr_vm_core/zrp_metadata.h"

TZrBool backend_aot_c_zrp_type_spec_row_is_retained(const SZrZrpMetadataTypeSpecRow *row,
                                                    const SZrMetadataTokenRecord *tokenRecords,
                                                    TZrUInt32 tokenRecordCount,
                                                    const SZrZrpMetadataMethodDefRow *methodRows,
                                                    TZrUInt32 methodCount,
                                                    const SZrZrpMetadataFieldDefRow *fieldRows,
                                                    TZrUInt32 fieldCount,
                                                    const SZrZrpMetadataTypeDefRow *typeRows,
                                                    TZrUInt32 typeCount,
                                                    const SZrZrpMetadataGenericParamRow *genericParamRows,
                                                    TZrUInt32 genericParamCount,
                                                    const SZrZrpMetadataGenericParamConstraintRow *genericParamConstraintRows,
                                                    TZrUInt32 genericParamConstraintCount,
                                                    const SZrAotFunctionTable *functionTable,
                                                    TZrUInt32 retainedMethodDefCount);
TZrMetadataToken backend_aot_c_zrp_compacted_type_spec_token(const SZrZrpMetadataTypeSpecRow *rows,
                                                            TZrUInt32 count,
                                                            TZrUInt32 typeSpecIndex,
                                                            const SZrMetadataTokenRecord *tokenRecords,
                                                            TZrUInt32 tokenRecordCount,
                                                            const SZrZrpMetadataMethodDefRow *methodRows,
                                                            TZrUInt32 methodCount,
                                                            const SZrZrpMetadataFieldDefRow *fieldRows,
                                                            TZrUInt32 fieldCount,
                                                            const SZrZrpMetadataTypeDefRow *typeRows,
                                                            TZrUInt32 typeCount,
                                                            const SZrZrpMetadataGenericParamRow *genericParamRows,
                                                            TZrUInt32 genericParamCount,
                                                            const SZrZrpMetadataGenericParamConstraintRow *genericParamConstraintRows,
                                                            TZrUInt32 genericParamConstraintCount,
                                                            const SZrAotFunctionTable *functionTable,
                                                            TZrUInt32 retainedMethodDefCount);
TZrBool backend_aot_c_zrp_remap_type_spec_token(TZrMetadataToken *token,
                                                const SZrZrpMetadataTypeSpecRow *rows,
                                                TZrUInt32 count,
                                                const SZrMetadataTokenRecord *tokenRecords,
                                                TZrUInt32 tokenRecordCount,
                                                const SZrZrpMetadataMethodDefRow *methodRows,
                                                TZrUInt32 methodCount,
                                                const SZrZrpMetadataFieldDefRow *fieldRows,
                                                TZrUInt32 fieldCount,
                                                const SZrZrpMetadataTypeDefRow *typeRows,
                                                TZrUInt32 typeCount,
                                                const SZrZrpMetadataGenericParamRow *genericParamRows,
                                                TZrUInt32 genericParamCount,
                                                const SZrZrpMetadataGenericParamConstraintRow *genericParamConstraintRows,
                                                TZrUInt32 genericParamConstraintCount,
                                                const SZrAotFunctionTable *functionTable,
                                                TZrUInt32 retainedMethodDefCount);
TZrBool backend_aot_c_zrp_remap_type_spec_tokens_in_record(SZrMetadataTokenRecord *record,
                                                           const SZrZrpMetadataTypeSpecRow *rows,
                                                           TZrUInt32 count,
                                                           const SZrMetadataTokenRecord *tokenRecords,
                                                           TZrUInt32 tokenRecordCount,
                                                           const SZrZrpMetadataMethodDefRow *methodRows,
                                                           TZrUInt32 methodCount,
                                                           const SZrZrpMetadataFieldDefRow *fieldRows,
                                                           TZrUInt32 fieldCount,
                                                           const SZrZrpMetadataTypeDefRow *typeRows,
                                                           TZrUInt32 typeCount,
                                                           const SZrZrpMetadataGenericParamRow *genericParamRows,
                                                           TZrUInt32 genericParamCount,
                                                           const SZrZrpMetadataGenericParamConstraintRow *genericParamConstraintRows,
                                                           TZrUInt32 genericParamConstraintCount,
                                                           const SZrAotFunctionTable *functionTable,
                                                           TZrUInt32 retainedMethodDefCount);
TZrUInt32 backend_aot_c_zrp_count_retained_type_specs(const SZrZrpMetadataTypeSpecRow *rows,
                                                      TZrUInt32 count,
                                                      const SZrMetadataTokenRecord *tokenRecords,
                                                      TZrUInt32 tokenRecordCount,
                                                      const SZrZrpMetadataMethodDefRow *methodRows,
                                                      TZrUInt32 methodCount,
                                                      const SZrZrpMetadataFieldDefRow *fieldRows,
                                                      TZrUInt32 fieldCount,
                                                      const SZrZrpMetadataTypeDefRow *typeRows,
                                                      TZrUInt32 typeCount,
                                                      const SZrZrpMetadataGenericParamRow *genericParamRows,
                                                      TZrUInt32 genericParamCount,
                                                      const SZrZrpMetadataGenericParamConstraintRow *genericParamConstraintRows,
                                                      TZrUInt32 genericParamConstraintCount,
                                                      const SZrAotFunctionTable *functionTable,
                                                      TZrUInt32 retainedMethodDefCount);
TZrBool backend_aot_c_zrp_copy_type_specs(TZrByte *targetBlob,
                                          const SZrZrpMetadataHeader *targetHeader,
                                          const SZrZrpMetadataTypeSpecRow *typeSpecRows,
                                          TZrUInt32 typeSpecCount,
                                          const SZrMetadataTokenRecord *tokenRecords,
                                          TZrUInt32 tokenRecordCount,
                                          const SZrZrpMetadataMethodDefRow *methodRows,
                                          TZrUInt32 methodCount,
                                          const SZrZrpMetadataFieldDefRow *fieldRows,
                                          TZrUInt32 fieldCount,
                                          const SZrZrpMetadataTypeDefRow *typeRows,
                                          TZrUInt32 typeCount,
                                          const SZrZrpMetadataGenericParamRow *genericParamRows,
                                          TZrUInt32 genericParamCount,
                                          const SZrZrpMetadataGenericParamConstraintRow *genericParamConstraintRows,
                                          TZrUInt32 genericParamConstraintCount,
                                          const SZrAotFunctionTable *functionTable,
                                          TZrUInt32 retainedMethodDefCount,
                                          const SZrAotCZrpSignatureBlobRemap *signatureRemap);

#endif
