#include "backend_aot_c_emitter.h"

void backend_aot_write_c_publish_exports(FILE *file) {
    if (file == ZR_NULL) {
        return;
    }

    fprintf(file,
            "    {\n"
            "        /* zr_aot_publish_exports_direct */\n"
            "        if (state == ZR_NULL || frame.function == ZR_NULL || frame.slotBase == ZR_NULL) {\n"
            "            ZR_AOT_C_FAIL();\n"
            "        }\n"
            "        if (frame.module == ZR_NULL || frame.moduleExecuted == ZR_NULL) {\n"
            "            ZR_AOT_C_FAIL();\n"
            "        }\n"
            "        if (!*frame.moduleExecuted) {\n"
            "            if (frame.function->exportedVariables == ZR_NULL || frame.function->exportedVariableLength == 0) {\n"
            "                *frame.moduleExecuted = ZR_TRUE;\n"
            "            } else {\n"
            "                TZrStackValuePointer zr_aot_exported_values_top = frame.slotBase + frame.function->stackSize;\n"
            "                for (TZrUInt32 zr_aot_export_index = 0; zr_aot_export_index < frame.function->exportedVariableLength; zr_aot_export_index++) {\n"
            "                    const SZrFunctionExportedVariable *zr_aot_export = &frame.function->exportedVariables[zr_aot_export_index];\n"
            "                    TZrStackValuePointer zr_aot_export_pointer;\n"
            "                    SZrTypeValue *zr_aot_export_value;\n"
            "                    SZrTypeValue zr_aot_published_value;\n"
            "                    SZrFunction *zr_aot_export_metadata_function;\n"
            "                    if (zr_aot_export->name == ZR_NULL) {\n"
            "                        continue;\n"
            "                    }\n"
            "                    zr_aot_export_pointer = frame.slotBase + zr_aot_export->stackSlot;\n"
            "                    if (zr_aot_export_pointer >= zr_aot_exported_values_top) {\n"
            "                        continue;\n"
            "                    }\n"
            "                    zr_aot_export_value = ZrCore_Stack_GetValue(zr_aot_export_pointer);\n"
            "                    if (zr_aot_export_value == ZR_NULL) {\n"
            "                        continue;\n"
            "                    }\n"
            "                    ZrCore_Value_ResetAsNull(&zr_aot_published_value);\n"
            "                    zr_aot_export_metadata_function = ZrCore_Closure_GetMetadataFunctionFromValue(state, zr_aot_export_value);\n"
            "                    if (zr_aot_export_metadata_function == ZR_NULL) {\n"
            "                        ZrCore_Value_Copy(state, &zr_aot_published_value, zr_aot_export_value);\n"
            "                    } else {\n");
    fprintf(file,
            "                        TZrUInt32 zr_aot_export_function_index = UINT32_MAX;\n"
            "                        if (frame.functionTable != ZR_NULL && frame.functionThunks != ZR_NULL) {\n"
            "                            for (TZrUInt32 zr_aot_candidate_index = 0; zr_aot_candidate_index < frame.functionCount &&\n"
            "                                 zr_aot_candidate_index < frame.functionThunkCount; zr_aot_candidate_index++) {\n"
            "                                if (frame.functionTable[zr_aot_candidate_index] == zr_aot_export_metadata_function) {\n"
            "                                    zr_aot_export_function_index = zr_aot_candidate_index;\n"
            "                                    break;\n"
            "                                }\n"
            "                            }\n"
            "                        }\n"
            "                        if (zr_aot_export_function_index == UINT32_MAX ||\n"
            "                            zr_aot_export_function_index >= frame.functionThunkCount ||\n"
            "                            frame.functionThunks[zr_aot_export_function_index] == ZR_NULL) {\n"
            "                            ZrCore_Debug_RunError(state, \"unsupported AOT module export callable without generated thunk\");\n"
            "                            ZR_AOT_C_FAIL();\n"
            "                        }\n"
            );
    fprintf(file,
            "                        if (zr_aot_export_metadata_function->closureValueLength == 0) {\n"
            "                            SZrClosureNative *zr_aot_export_closure = ZrCore_ClosureNative_New(state, 0);\n"
            "                            if (zr_aot_export_closure == ZR_NULL) {\n"
            "                                ZR_AOT_C_FAIL();\n"
            "                            }\n"
            "                            zr_aot_export_closure->nativeFunction = (FZrNativeFunction)frame.functionThunks[zr_aot_export_function_index];\n"
            "                            zr_aot_export_closure->aotShimFunction = zr_aot_export_metadata_function;\n"
            "                            ZrCore_Value_InitAsRawObject(state, &zr_aot_published_value, ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_export_closure));\n"
            "                            zr_aot_published_value.type = ZR_VALUE_TYPE_CLOSURE;\n"
            "                            zr_aot_published_value.isGarbageCollectable = ZR_TRUE;\n"
            "                            zr_aot_published_value.isNative = ZR_TRUE;\n"
            "                        } else {\n"
            "                            const TZrUInt32 zr_aot_export_capture_count = zr_aot_export_metadata_function->closureValueLength;\n"
            "                            TZrBool zr_aot_export_captures_bound = ZR_FALSE;\n"
            "                            SZrClosureNative *zr_aot_export_closure = ZrCore_ClosureNative_New(state, zr_aot_export_capture_count);\n"
            "                            SZrRawObject **zr_aot_export_capture_owners = ZR_NULL;\n"
            "                            if (zr_aot_export_closure == ZR_NULL) {\n"
            "                                ZR_AOT_C_FAIL();\n"
            "                            }\n"
            "                            zr_aot_export_closure->nativeFunction = (FZrNativeFunction)frame.functionThunks[zr_aot_export_function_index];\n"
            "                            zr_aot_export_closure->aotShimFunction = zr_aot_export_metadata_function;\n"
            "                            zr_aot_export_capture_owners = ZrCore_ClosureNative_GetCaptureOwners(zr_aot_export_closure);\n"
            );
    fprintf(file,
            "                            if (zr_aot_export_metadata_function->closureValueList != ZR_NULL && frame.slotBase != ZR_NULL) {\n"
            "                                const SZrTypeValue *zr_aot_current_closure_value = ZrCore_Stack_GetValue(frame.slotBase - 1);\n"
            "                                zr_aot_export_captures_bound = ZR_TRUE;\n"
            "                                for (TZrUInt32 zr_aot_capture_index = 0; zr_aot_capture_index < zr_aot_export_capture_count; zr_aot_capture_index++) {\n"
            "                                    const SZrFunctionClosureVariable *zr_aot_closure_variable = &zr_aot_export_metadata_function->closureValueList[zr_aot_capture_index];\n"
            "                                    SZrTypeValue *zr_aot_capture_value = ZR_NULL;\n"
            "                                    SZrRawObject *zr_aot_capture_owner = ZR_NULL;\n"
            "                                    if (zr_aot_closure_variable->inStack) {\n"
            "                                        SZrClosureValue *zr_aot_frame_closure_value =\n"
            "                                                ZrCore_Closure_FindOrCreateValue(state, frame.slotBase + zr_aot_closure_variable->index);\n"
            "                                        if (zr_aot_frame_closure_value != ZR_NULL) {\n"
            "                                            zr_aot_capture_value = ZrCore_ClosureValue_GetValue(zr_aot_frame_closure_value);\n"
            "                                            zr_aot_capture_owner = ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_frame_closure_value);\n"
            "                                        }\n"
            "                                    } else if (zr_aot_current_closure_value != ZR_NULL &&\n"
            "                                               zr_aot_current_closure_value->type == ZR_VALUE_TYPE_CLOSURE &&\n"
            "                                               zr_aot_current_closure_value->value.object != ZR_NULL) {\n"
            "                                        if (zr_aot_current_closure_value->isNative) {\n"
            "                                            SZrClosureNative *zr_aot_source_native_closure =\n"
            "                                                    ZR_CAST_NATIVE_CLOSURE(state, zr_aot_current_closure_value->value.object);\n"
            "                                            if (zr_aot_source_native_closure != ZR_NULL &&\n"
            "                                                zr_aot_closure_variable->index < zr_aot_source_native_closure->closureValueCount) {\n"
            "                                                zr_aot_capture_value = ZrCore_ClosureNative_GetCaptureValue(zr_aot_source_native_closure,\n"
            "                                                                                                             zr_aot_closure_variable->index);\n"
            "                                                zr_aot_capture_owner = ZrCore_ClosureNative_GetCaptureOwner(zr_aot_source_native_closure,\n"
            "                                                                                                             zr_aot_closure_variable->index);\n"
            "                                            }\n"
            );
    fprintf(file,
            "                                        } else {\n"
            "                                            SZrClosure *zr_aot_source_vm_closure =\n"
            "                                                    ZR_CAST_VM_CLOSURE(state, zr_aot_current_closure_value->value.object);\n"
            "                                            if (zr_aot_source_vm_closure != ZR_NULL &&\n"
            "                                                zr_aot_closure_variable->index < zr_aot_source_vm_closure->closureValueCount &&\n"
            "                                                zr_aot_source_vm_closure->closureValuesExtend[zr_aot_closure_variable->index] != ZR_NULL) {\n"
            "                                                SZrClosureValue *zr_aot_source_vm_closure_value =\n"
            "                                                        zr_aot_source_vm_closure->closureValuesExtend[zr_aot_closure_variable->index];\n"
            "                                                zr_aot_capture_value = ZrCore_ClosureValue_GetValue(zr_aot_source_vm_closure_value);\n"
            "                                                zr_aot_capture_owner = ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_source_vm_closure_value);\n"
            "                                            }\n"
            "                                        }\n"
            "                                    }\n"
            "                                    if (zr_aot_capture_value == ZR_NULL) {\n"
            "                                        zr_aot_export_captures_bound = ZR_FALSE;\n"
            "                                        break;\n"
            "                                    }\n"
            "                                    zr_aot_export_closure->closureValuesExtend[zr_aot_capture_index] = zr_aot_capture_value;\n"
            "                                    if (zr_aot_export_capture_owners != ZR_NULL) {\n"
            "                                        zr_aot_export_capture_owners[zr_aot_capture_index] = zr_aot_capture_owner;\n"
            "                                    }\n"
            "                                    if (zr_aot_capture_owner != ZR_NULL) {\n"
            "                                        ZrCore_RawObject_Barrier(state, ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_export_closure), zr_aot_capture_owner);\n"
            "                                    } else {\n"
            "                                        ZrCore_Value_Barrier(state, ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_export_closure), zr_aot_capture_value);\n"
            "                                    }\n"
            "                                }\n"
            "                            }\n");
    fprintf(file,
            "                            if (!zr_aot_export_captures_bound &&\n"
            "                                zr_aot_export_value->type == ZR_VALUE_TYPE_CLOSURE &&\n"
            "                                zr_aot_export_value->value.object != ZR_NULL) {\n"
            "                                zr_aot_export_captures_bound = ZR_TRUE;\n"
            "                                for (TZrUInt32 zr_aot_capture_index = 0; zr_aot_capture_index < zr_aot_export_capture_count; zr_aot_capture_index++) {\n"
            "                                    SZrTypeValue *zr_aot_capture_value = ZR_NULL;\n"
            "                                    SZrRawObject *zr_aot_capture_owner = ZR_NULL;\n"
            "                                    if (zr_aot_export_value->isNative) {\n"
            "                                        SZrClosureNative *zr_aot_source_native_closure =\n"
            "                                                ZR_CAST_NATIVE_CLOSURE(state, zr_aot_export_value->value.object);\n"
            "                                        if (zr_aot_source_native_closure != ZR_NULL &&\n"
            "                                            zr_aot_capture_index < zr_aot_source_native_closure->closureValueCount) {\n"
            "                                            zr_aot_capture_value = ZrCore_ClosureNative_GetCaptureValue(zr_aot_source_native_closure,\n"
            "                                                                                                         zr_aot_capture_index);\n"
            "                                            zr_aot_capture_owner = ZrCore_ClosureNative_GetCaptureOwner(zr_aot_source_native_closure,\n"
            "                                                                                                         zr_aot_capture_index);\n"
            "                                        }\n"
            );
    fprintf(file,
            "                                    } else {\n"
            "                                        SZrClosure *zr_aot_source_vm_closure =\n"
            "                                                ZR_CAST_VM_CLOSURE(state, zr_aot_export_value->value.object);\n"
            "                                        if (zr_aot_source_vm_closure != ZR_NULL &&\n"
            "                                            zr_aot_capture_index < zr_aot_source_vm_closure->closureValueCount &&\n"
            "                                            zr_aot_source_vm_closure->closureValuesExtend[zr_aot_capture_index] != ZR_NULL) {\n"
            "                                            SZrClosureValue *zr_aot_source_vm_closure_value =\n"
            "                                                    zr_aot_source_vm_closure->closureValuesExtend[zr_aot_capture_index];\n"
            "                                            zr_aot_capture_value = ZrCore_ClosureValue_GetValue(zr_aot_source_vm_closure_value);\n"
            "                                            zr_aot_capture_owner = ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_source_vm_closure_value);\n"
            "                                        }\n"
            "                                    }\n"
            "                                    if (zr_aot_capture_value == ZR_NULL) {\n"
            "                                        zr_aot_export_captures_bound = ZR_FALSE;\n"
            "                                        break;\n"
            "                                    }\n"
            "                                    zr_aot_export_closure->closureValuesExtend[zr_aot_capture_index] = zr_aot_capture_value;\n"
            "                                    if (zr_aot_export_capture_owners != ZR_NULL) {\n"
            "                                        zr_aot_export_capture_owners[zr_aot_capture_index] = zr_aot_capture_owner;\n"
            "                                    }\n"
            "                                    if (zr_aot_capture_owner != ZR_NULL) {\n"
            "                                        ZrCore_RawObject_Barrier(state, ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_export_closure), zr_aot_capture_owner);\n"
            "                                    } else {\n"
            "                                        ZrCore_Value_Barrier(state, ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_export_closure), zr_aot_capture_value);\n"
            "                                    }\n"
            "                                }\n"
            "                            }\n"
            );
    fprintf(file,
            "                            if (zr_aot_export_capture_count > 0 && !zr_aot_export_captures_bound) {\n"
            "                                ZrCore_Debug_RunError(state, \"unsupported AOT module export closure capture materialization\");\n"
            "                                ZR_AOT_C_FAIL();\n"
            "                            }\n"
            "                            ZrCore_Value_InitAsRawObject(state, &zr_aot_published_value, ZR_CAST_RAW_OBJECT_AS_SUPER(zr_aot_export_closure));\n"
            "                            zr_aot_published_value.type = ZR_VALUE_TYPE_CLOSURE;\n"
            "                            zr_aot_published_value.isGarbageCollectable = ZR_TRUE;\n"
            "                            zr_aot_published_value.isNative = ZR_TRUE;\n"
            "                        }\n"
            "                    }\n"
            "                    if (zr_aot_export->accessModifier == ZR_ACCESS_CONSTANT_PUBLIC) {\n"
            "                        ZrCore_Module_AddPubExport(state, frame.module, zr_aot_export->name, &zr_aot_published_value);\n"
            "                    } else if (zr_aot_export->accessModifier == ZR_ACCESS_CONSTANT_PROTECTED) {\n"
            "                        ZrCore_Module_AddProExport(state, frame.module, zr_aot_export->name, &zr_aot_published_value);\n"
            "                    }\n"
            "                }\n"
            "                *frame.moduleExecuted = ZR_TRUE;\n"
            "            }\n"
            "        }\n"
            "    }\n");
}
