#include <stdio.h>

#include "unity.h"
#include "zr_test_log_macros.h"

extern void test_function_parameter_handling(void);
extern void test_constant_deduplication(void);
extern void test_global_object_access(void);
extern void test_binary_expression_type_inference(void);
extern void test_nested_function_scope(void);
extern void test_closure_capture(void);
extern void test_complex_lvalue(void);
extern void test_external_variable_analysis(void);
extern void test_foreach_destructuring(void);
extern void test_switch_statement(void);
extern void test_generator_mechanism(void);
extern void test_function_call_type_inference(void);
extern void test_member_access_type_inference(void);
extern void test_type_conversion_instructions(void);
extern void test_function_call_argument_conversion_emits_to_float(void);
extern void test_type_expression_compiles_to_typeof_opcode(void);
extern void test_intermediate_writer_emits_type_metadata_section(void);
extern void test_intermediate_writer_emits_compile_time_and_test_metadata(void);
extern void test_compiler_optimizer_removes_dead_null_clear_streaks(void);
extern void test_compiler_optimizer_reuses_temp_slots_in_basic_blocks(void);
extern void test_member_and_index_access_emit_split_opcodes(void);
extern void test_global_member_access_emits_get_member(void);
extern void test_fixed_array_lowering_does_not_emit_length_member_write(void);
extern void test_foreach_emits_iterator_contract_opcodes(void);
extern void test_binary_writer_handles_exported_function_alias_with_unknown_parameter_types(void);
extern void test_compiler_escape_metadata_summarizes_capture_return_and_exports(void);
extern void test_binary_roundtrip_preserves_escape_metadata_summaries(void);
extern void test_compound_assignment_operators(void);
extern void test_variable_arguments_function(void);
extern void test_template_string_compilation_emits_string_pipeline(void);
extern void test_using_statement_compiles_through_frontend(void);
extern void test_owned_field_metadata_serializes_into_prototype_data(void);
extern void test_removed_field_scoped_using_does_not_serialize_metadata(void);
extern void test_advanced_oop_metadata_serializes_override_and_property_chains(void);
extern void test_abstract_class_construction_is_rejected_by_compiler(void);
extern void test_final_class_inheritance_is_rejected_by_compiler(void);
extern void test_override_of_non_virtual_member_is_rejected_by_compiler(void);
extern void test_inherited_same_name_requires_explicit_override_or_shadow(void);
extern void test_shadow_does_not_satisfy_abstract_base_member(void);
extern void test_interface_plain_member_serializes_interface_contract_slot(void);
extern void test_name_matched_iterator_members_without_builtin_interface_do_not_bind_contract_roles(void);
extern void test_interface_missing_member_is_rejected_by_compiler(void);
extern void test_ownership_builtin_shared_expression_consumes_unique_owner(void);
extern void test_ownership_borrow_loan_and_detach_emit_dedicated_opcodes(void);
extern void test_ownership_unique_share_runtime_moves_source_to_null(void);
extern void test_ownership_borrow_loan_and_detach_runtime_follow_surface_contract(void);
extern void test_ownership_weak_runtime_expires_to_null_after_last_shared_release(void);
extern void test_ownership_upgrade_and_release_runtime_follow_lifecycle_contract(void);
extern void test_ownership_release_preserves_unrelated_stack_values_after_weak_expiry(void);
extern void test_ownership_builtin_compile_rejects_invalid_operands(void);
extern void test_ownership_detach_runtime_rejects_multi_owner_shared_value(void);
extern void test_class_member_nested_functions_keep_constant_indices_in_range(void);
extern void test_lambda_create_closure_targets_are_reachable_from_child_function_graph(void);
extern void test_classes_full_module_compiles_without_static_and_receiver_signature_regressions(void);
extern void test_native_network_optional_argument_import_compiles_without_unknown_parameter_blowup(void);
extern void test_reserved_type_query_targets_compile_without_explicit_imports(void);
extern void test_qualified_container_types_compile_through_function_predeclaration_paths(void);
extern void test_native_network_loopback_runtime_returns_expected_payload(void);
extern void test_native_network_loopback_project_run_returns_expected_payload(void);
extern void test_imported_source_module_type_stubs_do_not_serialize_into_entry_prototype_data(void);
extern void test_project_local_struct_pair_shadows_native_pair_at_runtime(void);
extern void test_lsp_language_feature_matrix_runtime_returns_expected_total(void);
extern void test_lsp_language_feature_matrix_copy_runtime_keeps_top_level_closure_captures_stable(void);
extern void test_decorator_import_project_run_returns_expected_total(void);
extern void test_language_debug_gauntlet_project_run_returns_expected_banner_and_checksum(void);
extern void test_benchmark_numeric_loops_project_run_returns_expected_checksum(void);
extern void test_dispatch_loops_benchmark_project_runtime_keeps_step_member_pic_coverage(void);
extern void test_gc_fragment_stress_benchmark_project_run_returns_expected_checksum(void);
extern void test_matrix_add_2d_compile_avoids_adjacent_temp_reloads_before_super_array_int_ops(void);
extern void test_matrix_add_2d_compile_folds_right_hand_int_constants_into_const_opcodes(void);
extern void test_matrix_add_2d_compile_eliminates_temp_self_updates_for_add_int_const(void);
extern void test_matrix_add_2d_compile_folds_loop_bounds_into_sub_int_const(void);
extern void test_matrix_add_2d_compile_eliminates_forwardable_get_stack_copy_reads(void);
extern void test_matrix_add_2d_compile_fuses_less_equal_signed_jump_if_loop_guards(void);
extern void test_matrix_add_2d_compile_folds_direct_result_stores_into_final_slots(void);
extern void test_matrix_add_2d_compile_eliminates_zero_init_constant_copy_pairs(void);
extern void test_matrix_add_2d_compile_eliminates_generic_array_int_index_opcodes(void);
extern void test_matrix_add_2d_compile_emits_plain_destination_int_arithmetic_opcodes(void);
extern void test_strongly_typed_compile_prefers_typed_arithmetic_and_equality_opcodes(void);
extern void test_typed_quickening_promotes_const_and_plain_destination_variants(void);
extern void test_known_native_calls_quicken_to_dedicated_call_family(void);
extern void test_known_native_member_calls_quicken_to_dedicated_member_call_opcode(void);
extern void test_known_vm_member_call_load1_quickening_fuses_receiver_and_argument_loads(void);
extern void test_typed_member_calls_quicken_to_known_vm_call_family(void);
extern void test_typed_member_call_initializers_bind_directly_into_local_slots(void);
extern void test_typed_member_call_binary_operands_bind_directly_into_operand_slots(void);
extern void test_nested_argument_calls_do_not_reuse_tail_call_lowering(void);
extern void test_known_vm_call_results_keep_typed_arithmetic_specialization(void);
extern void test_direct_child_function_calls_quicken_to_known_vm_call_family(void);
extern void test_loop_child_function_calls_quicken_to_known_vm_call_family(void);
extern void test_map_object_access_benchmark_project_compile_quickens_labelFor_loop_call(void);
extern void test_repeated_constructor_string_arguments_survive_quickening_across_calls(void);
extern void test_initializer_bound_local_is_visible_on_next_source_line(void);
extern void test_noop_primitive_casts_do_not_emit_conversion_opcodes(void);
extern void test_logical_short_circuit_runtime_preserves_side_effect_boundaries(void);
extern void test_matrix_add_2d_compile_binds_super_array_items_for_hot_typed_int_paths(void);
extern void test_w2_load_typed_arithmetic_probe_reports_residual_candidates(void);

int main(void) {
    printf("\n");
    ZR_TEST_MODULE_DIVIDER();
    printf("ZR-VM Compiler Integration (features + regressions)\n");
    ZR_TEST_MODULE_DIVIDER();
    printf("\n");

    UNITY_BEGIN();

    printf("==========\n");
    printf("Basic Compiler Features Tests\n");
    printf("==========\n");
    RUN_TEST(test_function_parameter_handling);
    RUN_TEST(test_constant_deduplication);
    RUN_TEST(test_global_object_access);
    RUN_TEST(test_binary_expression_type_inference);
    RUN_TEST(test_nested_function_scope);

    printf("==========\n");
    printf("Expression Compilation Tests\n");
    printf("==========\n");
    RUN_TEST(test_closure_capture);
    RUN_TEST(test_complex_lvalue);
    RUN_TEST(test_external_variable_analysis);

    printf("==========\n");
    printf("Statement Compilation Tests\n");
    printf("==========\n");
    RUN_TEST(test_foreach_destructuring);
    RUN_TEST(test_switch_statement);
    RUN_TEST(test_generator_mechanism);

    printf("==========\n");
    printf("Type Inference Tests\n");
    printf("==========\n");
    RUN_TEST(test_function_call_type_inference);
    RUN_TEST(test_member_access_type_inference);
    RUN_TEST(test_type_conversion_instructions);
    RUN_TEST(test_function_call_argument_conversion_emits_to_float);
    RUN_TEST(test_type_expression_compiles_to_typeof_opcode);
    RUN_TEST(test_intermediate_writer_emits_type_metadata_section);
    RUN_TEST(test_intermediate_writer_emits_compile_time_and_test_metadata);
    RUN_TEST(test_compiler_optimizer_removes_dead_null_clear_streaks);
    RUN_TEST(test_compiler_optimizer_reuses_temp_slots_in_basic_blocks);
    RUN_TEST(test_member_and_index_access_emit_split_opcodes);
    RUN_TEST(test_global_member_access_emits_get_member);
    RUN_TEST(test_fixed_array_lowering_does_not_emit_length_member_write);
    RUN_TEST(test_foreach_emits_iterator_contract_opcodes);
    RUN_TEST(test_binary_writer_handles_exported_function_alias_with_unknown_parameter_types);
    RUN_TEST(test_compiler_escape_metadata_summarizes_capture_return_and_exports);
    RUN_TEST(test_binary_roundtrip_preserves_escape_metadata_summaries);

    printf("==========\n");
    printf("Advanced Features Tests\n");
    printf("==========\n");
    RUN_TEST(test_compound_assignment_operators);
    RUN_TEST(test_variable_arguments_function);
    RUN_TEST(test_template_string_compilation_emits_string_pipeline);
    RUN_TEST(test_using_statement_compiles_through_frontend);
    RUN_TEST(test_owned_field_metadata_serializes_into_prototype_data);
    RUN_TEST(test_removed_field_scoped_using_does_not_serialize_metadata);
    RUN_TEST(test_advanced_oop_metadata_serializes_override_and_property_chains);
    RUN_TEST(test_abstract_class_construction_is_rejected_by_compiler);
    RUN_TEST(test_final_class_inheritance_is_rejected_by_compiler);
    RUN_TEST(test_override_of_non_virtual_member_is_rejected_by_compiler);
    RUN_TEST(test_inherited_same_name_requires_explicit_override_or_shadow);
    RUN_TEST(test_shadow_does_not_satisfy_abstract_base_member);
    RUN_TEST(test_interface_plain_member_serializes_interface_contract_slot);
    RUN_TEST(test_name_matched_iterator_members_without_builtin_interface_do_not_bind_contract_roles);
    RUN_TEST(test_interface_missing_member_is_rejected_by_compiler);
    RUN_TEST(test_ownership_builtin_shared_expression_consumes_unique_owner);
    RUN_TEST(test_ownership_borrow_loan_and_detach_emit_dedicated_opcodes);
    RUN_TEST(test_ownership_unique_share_runtime_moves_source_to_null);
    RUN_TEST(test_ownership_borrow_loan_and_detach_runtime_follow_surface_contract);
    RUN_TEST(test_ownership_weak_runtime_expires_to_null_after_last_shared_release);
    RUN_TEST(test_ownership_upgrade_and_release_runtime_follow_lifecycle_contract);
    RUN_TEST(test_ownership_release_preserves_unrelated_stack_values_after_weak_expiry);
    RUN_TEST(test_ownership_builtin_compile_rejects_invalid_operands);
    RUN_TEST(test_ownership_detach_runtime_rejects_multi_owner_shared_value);

    printf("\n");
    ZR_TEST_MODULE_DIVIDER();
    printf("Compiler Regression Tests\n");
    ZR_TEST_MODULE_DIVIDER();
    printf("\n");

    RUN_TEST(test_class_member_nested_functions_keep_constant_indices_in_range);
    RUN_TEST(test_lambda_create_closure_targets_are_reachable_from_child_function_graph);
    RUN_TEST(test_classes_full_module_compiles_without_static_and_receiver_signature_regressions);
    RUN_TEST(test_native_network_optional_argument_import_compiles_without_unknown_parameter_blowup);
    RUN_TEST(test_reserved_type_query_targets_compile_without_explicit_imports);
    RUN_TEST(test_qualified_container_types_compile_through_function_predeclaration_paths);
    RUN_TEST(test_native_network_loopback_runtime_returns_expected_payload);
    RUN_TEST(test_native_network_loopback_project_run_returns_expected_payload);
    RUN_TEST(test_imported_source_module_type_stubs_do_not_serialize_into_entry_prototype_data);
    RUN_TEST(test_project_local_struct_pair_shadows_native_pair_at_runtime);
    RUN_TEST(test_lsp_language_feature_matrix_runtime_returns_expected_total);
    RUN_TEST(test_lsp_language_feature_matrix_copy_runtime_keeps_top_level_closure_captures_stable);
    RUN_TEST(test_decorator_import_project_run_returns_expected_total);
    RUN_TEST(test_language_debug_gauntlet_project_run_returns_expected_banner_and_checksum);
    RUN_TEST(test_benchmark_numeric_loops_project_run_returns_expected_checksum);
    RUN_TEST(test_dispatch_loops_benchmark_project_runtime_keeps_step_member_pic_coverage);
    RUN_TEST(test_gc_fragment_stress_benchmark_project_run_returns_expected_checksum);
    RUN_TEST(test_matrix_add_2d_compile_avoids_adjacent_temp_reloads_before_super_array_int_ops);
    RUN_TEST(test_matrix_add_2d_compile_folds_right_hand_int_constants_into_const_opcodes);
    RUN_TEST(test_matrix_add_2d_compile_eliminates_temp_self_updates_for_add_int_const);
    RUN_TEST(test_matrix_add_2d_compile_folds_loop_bounds_into_sub_int_const);
    RUN_TEST(test_matrix_add_2d_compile_eliminates_forwardable_get_stack_copy_reads);
    RUN_TEST(test_matrix_add_2d_compile_fuses_less_equal_signed_jump_if_loop_guards);
    RUN_TEST(test_matrix_add_2d_compile_folds_direct_result_stores_into_final_slots);
    RUN_TEST(test_matrix_add_2d_compile_eliminates_zero_init_constant_copy_pairs);
    RUN_TEST(test_matrix_add_2d_compile_eliminates_generic_array_int_index_opcodes);
    RUN_TEST(test_matrix_add_2d_compile_emits_plain_destination_int_arithmetic_opcodes);
    RUN_TEST(test_strongly_typed_compile_prefers_typed_arithmetic_and_equality_opcodes);
    RUN_TEST(test_typed_quickening_promotes_const_and_plain_destination_variants);
    RUN_TEST(test_known_native_calls_quicken_to_dedicated_call_family);
    RUN_TEST(test_known_native_member_calls_quicken_to_dedicated_member_call_opcode);
    RUN_TEST(test_known_vm_member_call_load1_quickening_fuses_receiver_and_argument_loads);
    RUN_TEST(test_typed_member_calls_quicken_to_known_vm_call_family);
    RUN_TEST(test_typed_member_call_initializers_bind_directly_into_local_slots);
    RUN_TEST(test_typed_member_call_binary_operands_bind_directly_into_operand_slots);
    RUN_TEST(test_nested_argument_calls_do_not_reuse_tail_call_lowering);
    RUN_TEST(test_known_vm_call_results_keep_typed_arithmetic_specialization);
    RUN_TEST(test_direct_child_function_calls_quicken_to_known_vm_call_family);
    RUN_TEST(test_loop_child_function_calls_quicken_to_known_vm_call_family);
    RUN_TEST(test_map_object_access_benchmark_project_compile_quickens_labelFor_loop_call);
    RUN_TEST(test_repeated_constructor_string_arguments_survive_quickening_across_calls);
    RUN_TEST(test_initializer_bound_local_is_visible_on_next_source_line);
    RUN_TEST(test_noop_primitive_casts_do_not_emit_conversion_opcodes);
    RUN_TEST(test_logical_short_circuit_runtime_preserves_side_effect_boundaries);
    RUN_TEST(test_matrix_add_2d_compile_binds_super_array_items_for_hot_typed_int_paths);
    RUN_TEST(test_w2_load_typed_arithmetic_probe_reports_residual_candidates);

    printf("\n");
    ZR_TEST_MODULE_DIVIDER();
    printf("All Compiler Integration Tests Completed\n");
    ZR_TEST_MODULE_DIVIDER();
    printf("\n");

    return UNITY_END();
}
