#ifndef ZR_TEST_OWNERSHIP_ABRUPT_PARITY_CASES_H
#define ZR_TEST_OWNERSHIP_ABRUPT_PARITY_CASES_H

#define ZR_TEST_OWNERSHIP_ABRUPT_PARITY_EXPECTED 123456778908LL

static const char *ownership_abrupt_parity_source(void) {
    return "resource class Leaf {\n"
           " pub static var drops: int = 0;\n"
           " pub static var trace: int = 0;\n"
           " pub var value: int;\n"
           " pub @constructor(value: int) { this.value = value; }\n"
           " pub @destructor() { Leaf.drops = Leaf.drops + 1; }\n"
           "}\n"
           "resource class Branch {\n"
           " pub var leaf: Shared<Leaf>;\n"
           " pub @constructor(leaf: Shared<Leaf>) { this.leaf = leaf; }\n"
           " pub @destructor() { Leaf.drops = Leaf.drops + 1; }\n"
           "}\n"
           "resource class Root {\n"
           " pub var branch: Weak<Branch>;\n"
           " pub @constructor(branch: Weak<Branch>) { this.branch = branch; }\n"
           " pub @destructor() { Leaf.drops = Leaf.drops + 1; }\n"
           "}\n"
           "fn sharedReturn(owner: Shared<Leaf>): Shared<Leaf> {\n"
           " try { try { return owner; } finally {\n"
           "  Leaf.trace = Leaf.trace * 10 + 1;\n"
           " } } finally { Leaf.trace = Leaf.trace * 10 + 2; }\n"
           "}\n"
           "fn weakReturn(owner: Shared<Leaf>): Weak<Leaf> {\n"
           " var weak = degrade(owner);\n"
           " try { try { return weak; } finally {\n"
           "  Leaf.trace = Leaf.trace * 10 + 3;\n"
           " } } finally { Leaf.trace = Leaf.trace * 10 + 4; }\n"
           "}\n"
           "fn abandonedReturn(owner: Shared<Leaf>): Shared<Leaf> {\n"
           " try { return owner; } finally {\n"
           "  Leaf.trace = Leaf.trace * 10 + 5; throw \"replacement\";\n"
           " }\n"
           "}\n"
           "fn chainReturn(root: Weak<Root>): Shared<Leaf> { return root.branch.leaf; }\n"
           "fn sharedCase(): int {\n"
           " var seed = own Leaf(11); var shared = share(seed);\n"
           " var returned = sharedReturn(shared); drop(shared);\n"
           " if (Leaf.drops != 0 || returned.value != 11) { return -1; }\n"
           " drop(returned); return Leaf.drops;\n"
           "}\n"
           "fn weakCase(): int {\n"
           " var seed = own Leaf(22); var shared = share(seed);\n"
           " var returned = weakReturn(shared); drop(shared);\n"
           " var expired = wake(returned);\n"
           " if (expired != null) { return -1; }\n"
           " drop(returned); return Leaf.drops;\n"
           "}\n"
           "fn overrideCase(): int {\n"
           " var seed = own Leaf(33); var shared = share(seed);\n"
           " try { var returned = abandonedReturn(shared); } catch (error) {\n"
           "  Leaf.trace = Leaf.trace * 10 + 6;\n"
           " }\n"
           " drop(shared); return Leaf.drops;\n"
           "}\n"
           "fn loopCase(): int {\n"
           " var i = 0;\n"
           " try { while (i < 2) { try {\n"
           "  var seed = own Leaf(i); var shared = share(seed);\n"
           "  i = i + 1; if (i < 2) { continue; } break;\n"
           " } finally { Leaf.trace = Leaf.trace * 10 + 7; }\n"
           " } Leaf.trace = Leaf.trace * 10 + 8;\n"
           " } finally { Leaf.trace = Leaf.trace * 10 + 9; }\n"
           " return Leaf.drops;\n"
           "}\n"
           "fn chainCase(): int {\n"
           " var leafSeed = own Leaf(73); var leafShared = share(leafSeed);\n"
           " var branchSeed = own Branch(leafShared); var branchShared = share(branchSeed);\n"
           " var branchWeak = degrade(branchShared);\n"
           " var rootSeed = own Root(branchWeak); var rootShared = share(rootSeed);\n"
           " var rootWeak = degrade(rootShared);\n"
           " var returned = chainReturn(rootWeak);\n"
           " drop(rootShared); drop(branchShared); drop(leafShared);\n"
           " if (Leaf.drops != 7 || returned.value != 73) { return -1; }\n"
           " if (wake(rootWeak) != null || wake(branchWeak) != null) { return -2; }\n"
           " drop(returned); drop(rootWeak); drop(branchWeak);\n"
           " return Leaf.drops;\n"
           "}\n"
           "fn run(): int {\n"
           " if (sharedCase() != 1) { return -11; }\n"
           " if (weakCase() != 2) { return -12; }\n"
           " if (overrideCase() != 3) { return -13; }\n"
           " if (loopCase() != 5) { return -14; }\n"
           " if (chainCase() != 8) { return -15; }\n"
           " return Leaf.trace * 100 + Leaf.drops;\n"
           "}\n"
           "return run();\n";
}

#endif
