#include "unity.h"

void test_matrix_add_2d_compile_binds_super_array_items_for_hot_typed_int_paths(void);
void test_w2_load_typed_arithmetic_probe_reports_residual_candidates(void);
void test_w2_dispatch_loops_materialized_constant_signed_arithmetic_fuses(void);
void test_w2_signed_equality_branch_fuses_slot_operands(void);
void test_w2_signed_greater_equal_branch_reuses_greater_signed_jump(void);
void test_w2_signed_greater_branch_fuses_to_less_equal_jump(void);
void test_w2_static_iterator_move_next_branch_fuses(void);
void test_w2_static_iterator_plain_dest_state_does_not_cross_loop_exit(void);
void test_w2_super_array_add_variable_value_elides_dead_receiver_setup(void);
void test_w2_get_member_slot_direct_result_store_elides_temp_copy(void);
void test_w2_known_native_member_call_skips_argument_loads(void);
void test_w2_set_member_slot_null_fuses_dead_null_temp(void);
void test_w2_set_member_slot_null_does_not_kill_slot_zero_forwarding(void);
void test_w2_set_member_slot_cache_index_does_not_kill_slot_zero_forwarding(void);
void test_w2_set_member_slot_receiver_forwarding_rewrites_receiver(void);
void test_w2_null_not_equal_branch_fuses_dead_null_temp(void);
void test_w2_get_stack_set_member_slot_value_forwards_source(void);
void test_w2_left_constant_add_mul_fold_to_existing_const_opcodes(void);
void test_w2_right_constant_mod_fold_uses_cfg_liveness_across_branch(void);
void test_w2_late_forward_get_stack_after_member_call_specialization(void);

int main(void) {
    UNITY_BEGIN();

    RUN_TEST(test_matrix_add_2d_compile_binds_super_array_items_for_hot_typed_int_paths);
    RUN_TEST(test_w2_load_typed_arithmetic_probe_reports_residual_candidates);
    RUN_TEST(test_w2_dispatch_loops_materialized_constant_signed_arithmetic_fuses);
    RUN_TEST(test_w2_signed_equality_branch_fuses_slot_operands);
    RUN_TEST(test_w2_signed_greater_equal_branch_reuses_greater_signed_jump);
    RUN_TEST(test_w2_signed_greater_branch_fuses_to_less_equal_jump);
    RUN_TEST(test_w2_static_iterator_move_next_branch_fuses);
    RUN_TEST(test_w2_static_iterator_plain_dest_state_does_not_cross_loop_exit);
    RUN_TEST(test_w2_super_array_add_variable_value_elides_dead_receiver_setup);
    RUN_TEST(test_w2_get_member_slot_direct_result_store_elides_temp_copy);
    RUN_TEST(test_w2_known_native_member_call_skips_argument_loads);
    RUN_TEST(test_w2_set_member_slot_null_fuses_dead_null_temp);
    RUN_TEST(test_w2_set_member_slot_null_does_not_kill_slot_zero_forwarding);
    RUN_TEST(test_w2_set_member_slot_cache_index_does_not_kill_slot_zero_forwarding);
    RUN_TEST(test_w2_set_member_slot_receiver_forwarding_rewrites_receiver);
    RUN_TEST(test_w2_null_not_equal_branch_fuses_dead_null_temp);
    RUN_TEST(test_w2_get_stack_set_member_slot_value_forwards_source);
    RUN_TEST(test_w2_left_constant_add_mul_fold_to_existing_const_opcodes);
    RUN_TEST(test_w2_right_constant_mod_fold_uses_cfg_liveness_across_branch);
    RUN_TEST(test_w2_late_forward_get_stack_after_member_call_specialization);

    return UNITY_END();
}
