//
// CLI-local configuration constants.
//

#ifndef ZR_VM_CLI_CONF_H
#define ZR_VM_CLI_CONF_H

#include "zr_vm_common.h"

#define ZR_CLI_API ZR_API

#define ZR_CLI_ERROR_BUFFER_LENGTH 512U
#define ZR_CLI_SOURCE_HASH_HEX_LENGTH 32U
#define ZR_CLI_REPL_LINE_BUFFER_LENGTH 1024U
#define ZR_CLI_REPL_BUFFER_INITIAL_CAPACITY 256U
#define ZR_CLI_COLLECTION_INITIAL_CAPACITY 8U
#define ZR_CLI_SMALL_COLLECTION_INITIAL_CAPACITY 4U
#define ZR_CLI_COLLECTION_GROWTH_FACTOR 2U

#endif // ZR_VM_CLI_CONF_H
